apiVersion: v1
kind: Service
metadata:
  name: barca-redis
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: barca-redis
  ports:
    - name: barca-redis
      port: 6379
      targetPort: 6379
