version: '3.9'
services:
  redis:
    container_name: redis_container
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --loglevel warning
    volumes:
      - ./docker-volumes/cache:/data
    networks:
      - elastic

  mongodb:
    container_name: mongodb_container
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./docker-volumes/data:/data/db
    networks:
      - elastic

  mysql:
    container_name: mysql_container
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_USER=barca
      - MYSQL_DATABASE=barca_auth
      - MYSQL_ROOT_PASSWORD=api
      - MYSQL_PASSWORD=api
    ports:
      - 3306:3306
    volumes:
      - ./docker-volumes/mysql:/var/lib/mysql
    networks:
      - elastic

  psql:
    container_name: psql_container
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=barca
      - POSTGRES_DB=barca-review
      - POSTGRES_PASSWORD=api
    ports:
      - 5432:5432
    volumes:
      - ./docker-volumes/postgres:/var/lib/postgresql
    networks:
      - elastic

  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:3.13-rc-management-alpine
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=barca
      - RABBITMQ_DEFAULT_PASS=barcapass
    ports:
      # AMQP
      - 5672:5672
      # Dashboard
      - 15672:15672
    networks:
      - elastic

  elasticsearch:
    container_name: elasticsearch_container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    restart: always
    environment:
      ES_JAVA_OPTS: -Xmx1g -Xms1g
      bootstrap.memory_lock: 'true'
      discovery.type: single-node
      network.host: 0.0.0.0
      transport.host: 127.0.0.1
      http.host: 0.0.0.0
      xpack.security.enabled: 'true'
      xpack.security.authc.api_key.enabled: 'true'
      xpack.monitoring.collection.enabled: 'true'
      xpack.security.enrollment.enabled: 'true'
      xpack.security.authc.token.enabled: 'true'
      ELASTIC_PASSWORD: admin1234
    ports:
      - 9300:9300
      - 9200:9200
    volumes:
      - ./docker-volumes/elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana:
    container_name: kibana_container
    image: docker.elastic.co/kibana/kibana:8.11.1
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=["http://elasticsearch_container:9200"]
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=kibana
      - ELASTICSEARCH_SERVICEACCOUNT_TOKEN=QUFFQUFXVnNZWE4wYVdNdlpteGxaWFF0YzJWeWRtVnlMMkpoY21OaFgydHBZbUZ1WVRwaVRrWjFUM1l5TUZSVWJUZEhkWGx4YlRsQ1QwbDM=
      - XPACK_FLEET_AGENTS_ELASTICSEARCH_HOSTS=["http://elasticsearch_container:9200"]
    ports:
      - 5601:5601
    networks:
      - elastic
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    depends_on:
      - elasticsearch

  apmServer:
    container_name: apm_server_container
    image: docker.elastic.co/apm/apm-server:8.11.1
    ports:
      - 8200:8200
    volumes:
      - ./apm-server.yml:/usr/share/apm-server/apm-server.yml:ro
    networks:
      - elastic
    command: >
      apm-server -e
        -E apm-server.rum.enabled=true
        -E setup.kibana.host=kibana_container:5601
        -E setup.template.settings.index.number_of_replicas=0
        -E apm-server.kibana.enabled=true
        -E apm-server.kibana.host=kibana_container:5601
        -E apm-server.kibana.protocol=http
        -E strict.perms=false
        -E apm-server.auth.anonymous.enabled=true

  metricbeat:
    container_name: metricbeat_container
    image: docker.elastic.co/beats/metricbeat:8.11.1
    user: root
    ports:
      - 5066:5066
    networks:
      - elastic
    volumes:
      - ./metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
    command: ['--strict.perms=false', '-system.hostfs=/hostfs']
    depends_on:
      - elasticsearch

  heartbeat:
    container_name: heartbeat_container
    image: docker.elastic.co/beats/heartbeat:8.11.1
    user: root
    hostname: heartbeat
    cap_add:
      - NET_RAW
    networks:
      - elastic
    volumes:
      - ./heartbeat.yml:/usr/share/heartbeat/heartbeat.yml:ro
    command: ['--strict.perms=false']
    depends_on:
      - elasticsearch

  gateway:
    container_name: gateway_container
    build:
      context: .
      dockerfile: ./packages/gateway-service/Dockerfile.dev
    ports:
      - 4000:4000
    env_file: ./packages/gateway-service/.env
    environment:
      - ENABLE_APM=0
      - GATEWAY_JWT_TOKEN=4a0ea5289e11618219f1488e25b2
      - JWT_TOKEN=fde8dd24118e4bab218c498d317a
      - NODE_ENV=development
      - SECRET_KEY_ONE=9c5b26438c8d7f7dac12607661f3
      - SECRET_KEY_TWO=3e0b0c40b1a8ceeb5979056abbf6
      - CLIENT_URL=http://localhost:3000
      - AUTH_BASE_URL=http://auth_container:4002
      - USERS_BASE_URL=http://user_container:4003
      - GIG_BASE_URL=http://gig_container:4004
      - MESSAGE_BASE_URL=http://chat_container:4005
      - ORDER_BASE_URL=http://order_container:4006
      - REVIEW_BASE_URL=http://review_container:4007
      - REDIS_HOST=redis://redis_container:6379
      - RABBITMQ_ENDPOINT=amqp://barca:barcapass@rabbitmq:5672
      - ELASTIC_SEARCH_URL=http://elasticsearch_container:9200
      - ELASTIC_APM_SERVER_URL=http://apm_server_container:8200
      - ELASTIC_APM_SECRET_TOKEN=
    depends_on:
      - elasticsearch
    networks:
      - elastic

  notification:
    container_name: notification_container
    build:
      context: .
      dockerfile: ./packages/notification-service/Dockerfile.dev
    ports:
      - 4001:4001
    env_file: ./packages/notification-service/.env
    environment:
      - ENABLE_APM=0
      - NODE_ENV=development
      - CLIENT_URL=http://localhost:3000
      - SENDER_EMAIL=lysanne.rutherford88@ethereal.email
      - SENDER_EMAIL_PASSWORD=ad8y45AkfebKmW8rCV
      - RABBITMQ_ENDPOINT=amqp://barca:barcapass@rabbitmq:5672
      - ELASTIC_SEARCH_URL=http://elasticsearch_container:9200
      - ELASTIC_APM_SERVER_URL=http://apm_server_container:8200
      - ELASTIC_APM_SECRET_TOKEN=
    depends_on:
      - elasticsearch
    networks:
      - elastic

  auth:
    container_name: auth_container
    build:
      context: .
      dockerfile: ./packages/auth-service/Dockerfile.dev
    ports:
      - 4002:4002
    env_file: ./packages/auth-service/.env
    environment:
      - ENABLE_APM=0
      - GATEWAY_JWT_TOKEN=4a0ea5289e11618219f1488e25b2
      - JWT_TOKEN=fde8dd24118e4bab218c498d317a
      - NODE_ENV=development
      - API_GATEWAY_URL=http://gateway_container:4000
      - CLIENT_URL=http://localhost:3000
      - DATABASE_URL=mysql://barca:api@mysql_container:3306/barca_auth
      - CLOUD_NAME=dcxbaieik
      - CLOUD_API_KEY=879258555729797
      - CLOUD_API_SECRET=g7LKyW01gIligdi2B4nCpxDPn6E
      - RABBITMQ_ENDPOINT=amqp://barca:barcapass@rabbitmq:5672
      - ELASTIC_SEARCH_URL=http://elasticsearch_container:9200
      - ELASTIC_APM_SERVER_URL=http://apm_server_container:8200
      - ELASTIC_APM_SECRET_TOKEN=
    depends_on:
      - elasticsearch
      - mysql
    networks:
      - elastic

  user:
    container_name: user_container
    build:
      context: .
      dockerfile: ./packages/user-service/Dockerfile.dev
    ports:
      - 4003:4003
    env_file: ./packages/user-service/.env
    environment:
      - ENABLE_APM=0
      - DATABASE_URL=mongodb://mongodb_container:27017/barca-user
      - GATEWAY_JWT_TOKEN=4a0ea5289e11618219f1488e25b2
      - JWT_TOKEN=fde8dd24118e4bab218c498d317a
      - NODE_ENV=development
      - API_GATEWAY_URL=http://gateway_container:4000
      - CLOUD_NAME=dcxbaieik
      - CLOUD_API_KEY=879258555729797
      - CLOUD_API_SECRET=g7LKyW01gIligdi2B4nCpxDPn6E
      - REDIS_HOST=redis://redis_container:6379
      - RABBITMQ_ENDPOINT=amqp://barca:barcapass@rabbitmq:5672
      - ELASTIC_SEARCH_URL=http://elasticsearch_container:9200
      - ELASTIC_APM_SERVER_URL=http://apm_server_container:8200
      - ELASTIC_APM_SECRET_TOKEN=
    depends_on:
      - elasticsearch
      - mongodb
    networks:
      - elastic

  gig:
    container_name: gig_container
    build:
      context: .
      dockerfile: ./packages/gig-service/Dockerfile.dev
    ports:
      - 4004:4004
    env_file: ./packages/gig-service/.env
    environment:
      - ENABLE_APM=0
      - DATABASE_URL=mongodb://mongodb_container:27017/barca-gig
      - GATEWAY_JWT_TOKEN=4a0ea5289e11618219f1488e25b2
      - JWT_TOKEN=fde8dd24118e4bab218c498d317a
      - NODE_ENV=development
      - API_GATEWAY_URL=http://gateway_container:4000
      - CLOUD_NAME=dcxbaieik
      - CLOUD_API_KEY=879258555729797
      - CLOUD_API_SECRET=g7LKyW01gIligdi2B4nCpxDPn6E
      - REDIS_HOST=redis://redis_container:6379
      - RABBITMQ_ENDPOINT=amqp://barca:barcapass@rabbitmq:5672
      - ELASTIC_SEARCH_URL=http://elasticsearch_container:9200
      - ELASTIC_APM_SERVER_URL=http://apm_server_container:8200
      - ELASTIC_APM_SECRET_TOKEN=
    depends_on:
      - elasticsearch
      - mongodb
    networks:
      - elastic

  chat:
    container_name: chat_container
    build:
      context: .
      dockerfile: ./packages/chat-service/Dockerfile.dev
    ports:
      - 4005:4005
    env_file: ./packages/chat-service/.env
    environment:
      - ENABLE_APM=0
      - DATABASE_URL=mongodb://mongodb_container:27017/barca-chat
      - GATEWAY_JWT_TOKEN=4a0ea5289e11618219f1488e25b2
      - JWT_TOKEN=fde8dd24118e4bab218c498d317a
      - NODE_ENV=development
      - API_GATEWAY_URL=http://gateway_container:4000
      - CLOUD_NAME=dcxbaieik
      - CLOUD_API_KEY=879258555729797
      - CLOUD_API_SECRET=g7LKyW01gIligdi2B4nCpxDPn6E
      - RABBITMQ_ENDPOINT=amqp://barca:barcapass@rabbitmq:5672
      - ELASTIC_SEARCH_URL=http://elasticsearch_container:9200
      - ELASTIC_APM_SERVER_URL=http://apm_server_container:8200
      - ELASTIC_APM_SECRET_TOKEN=
    depends_on:
      - elasticsearch
      - mongodb
    networks:
      - elastic

  order:
    container_name: order_container
    build:
      context: .
      dockerfile: ./packages/order-service/Dockerfile.dev
    ports:
      - 4006:4006
    env_file: ./packages/order-service/.env
    environment:
      - ENABLE_APM=0
      - DATABASE_URL=mongodb://mongodb_container:27017/barca-chat
      - GATEWAY_JWT_TOKEN=4a0ea5289e11618219f1488e25b2
      - JWT_TOKEN=fde8dd24118e4bab218c498d317a
      - NODE_ENV=development
      - API_GATEWAY_URL=http://gateway_container:4000
      - CLIENT_URL=http://localhost:3000
      - STRIPE_API_KEY=sk_test_51OR3pLFkSGcuWDFzIWvUaCbl9qtR2vwkuncJ8KsmtSjinhPgxZAVbCFMnRtrGbQ154MS0ZVKFp6KIkqJRMvqyLxW00c6ROGl2k
      - CLOUD_NAME=dcxbaieik
      - CLOUD_API_KEY=879258555729797
      - CLOUD_API_SECRET=g7LKyW01gIligdi2B4nCpxDPn6E
      - RABBITMQ_ENDPOINT=amqp://barca:barcapass@rabbitmq:5672
      - ELASTIC_SEARCH_URL=http://elasticsearch_container:9200
      - ELASTIC_APM_SERVER_URL=http://apm_server_container:8200
      - ELASTIC_APM_SECRET_TOKEN=
    depends_on:
      - elasticsearch
      - mongodb
    networks:
      - elastic

  review:
    container_name: review_container
    build:
      context: .
      dockerfile: ./packages/review-service/Dockerfile.dev
    ports:
      - 4007:4007
    env_file: ./packages/review-service/.env
    environment:
      - ENABLE_APM=0
      - DATABASE_HOST=192.168.0.42
      - DATABASE_USER=barca
      - DATABASE_PASSWORD=api
      - DATABASE_NAME=barca-review
      - GATEWAY_JWT_TOKEN=4a0ea5289e11618219f1488e25b2
      - JWT_TOKEN=fde8dd24118e4bab218c498d317a
      - NODE_ENV=development
      - API_GATEWAY_URL=http://gateway_container:4000
      - CLOUD_NAME=dcxbaieik
      - CLOUD_API_KEY=879258555729797
      - CLOUD_API_SECRET=g7LKyW01gIligdi2B4nCpxDPn6E
      - RABBITMQ_ENDPOINT=amqp://barca:barcapass@rabbitmq:5672
      - ELASTIC_SEARCH_URL=http://elasticsearch_container:9200
      - ELASTIC_APM_SERVER_URL=http://apm_server_container:8200
      - ELASTIC_APM_SECRET_TOKEN=
    depends_on:
      - elasticsearch
      - psql
    networks:
      - elastic

  jenkins:
    container_name: jenkins_container
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./docker-volumes/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  jenkins-agent:
    container_name: jenkins_agent_container
    image: jenkins/ssh-agent:jdk11
    privileged: true
    user: root
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDeGb5smWhdHUSb+WpVdhVGZcB/xzSnc+kzRyN3sgCRnuBTZpNv3H9BjcS0AZuoFeEc4baE+93Q534dB/BIcUdwrR6NBSNjkj9DqSTRu5CUd2RV5dfrY8b7XAi3ByJn/DrLEXSPCpkkXEo7kaIeKf7hIi1VXs5ow4EGdg9+wRezuxPpPg8LUadXi54bZuWn2/P3qsnVBhLGHjZ5Gxnr3nBEwsT5cq0dXCUVqQ+HSO0x5EUmKpAvKGLqXCs8Y7cpVtKmnahfVF08KplSNrQW5QsjNqF6cYbvUomYbKCVKAt205vTHDmoiywNaeJEuGVyu6BASlzqCTasRfGGcvNyv5RjetfnJuv4YhhuqRi/UQ5QFJYGsAf9DBzesYvj8ljh9nQ7/KVQJdTX5sx/eqS0Pwq980bynCwozzdHZj21KvfYuqnHDJaPLpAccimAMTl+cxbUyNHCVXwAQp4r25jUpTjS7vARC61+ShkGA5807IFUs8J1G6XmTIySsk7qEWIQhx8= joseph0926@DESKTOP-T6FAK8A

networks:
  elastic:
    name: elastic
# docker compose up -d redis mongodb mysql psql rabbitmq elasticsearch kibana metricbeat heartbeat gateway auth user notification gig order review chat jenkins jenkins-agent

# docker compose up -d gateway auth user notification gig order review chat
