apiVersion: apps/v1
kind: Deployment
metadata:
  name: barca-rabbitmq
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: barca-rabbitmq
  template:
    metadata:
      labels:
        app: barca-rabbitmq
    spec:
      containers:
        - name: barca-rabbitmq
          image: rabbitmq:3.13-rc-management-alpine
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: barca-secret
                  key: barca-rabbitmq-user
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: barca-secret
                  key: barca-rabbitmq-password
          resources:
            limits:
              memory: '1Gi'
              cpu: '0.5'
            requests:
              memory: 150Mi
              cpu: 100m
          ports:
            - name: rabbitmq
              containerPort: 5672
              protocol: TCP
            - name: management
              containerPort: 15672
              protocol: TCP
          volumeMounts:
            - name: rabbitmq-local-storage
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: rabbitmq-local-storage
          persistentVolumeClaim:
            claimName: rabbitmq-pvc
