apiVersion: v1
kind: Service
metadata:
  name: barca-rabbitmq
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: barca-rabbitmq
  ports:
    - name: rabbitmq
      port: 5672
      targetPort: rabbitmq
      protocol: TCP
    - name: management
      port: 15672
      targetPort: rabbitmq
      protocol: TCP
