apiVersion: v1
kind: Service
metadata:
  name: barca-user
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: barca-user
  ports:
    - name: user
      port: 4003
      targetPort: 4003
      protocol: TCP
