apiVersion: v1
kind: Service
metadata:
  name: barca-mongo
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: barca-mongo
  ports:
    - name: barca-mongo
      port: 27017
      targetPort: 27017
