apiVersion: apps/v1
kind: Deployment
metadata:
  name: barca-auth
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: barca-auth
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: barca-auth
    spec:
      containers:
        - name: barca-auth
          image: joseph0926/barca-auth:stable
          imagePullPolicy: Always
          resources:
            limits:
              cpu: '0.5'
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 150Mi
          ports:
            - name: auth
              containerPort: 4002
          env:
            - name: ENABLE_APM
              value: '1'
            - name: NODE_ENV
              value: 'production'
            - name: GATEWAY_JWT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: barca-secret
                  key: gateway-jwt-token
            - name: JWT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: barca-secret
                  key: jwt-token
            - name: RABBITMQ_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: barca-secret
                  key: barca-rabbitmq-endpoint
            - name: MYSQL_DB
              valueFrom:
                secretKeyRef:
                  name: barca-secret
                  key: barca-mysql-db
            - name: CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: barca-secret
                  key: cloud-name
            - name: CLOUD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: barca-secret
                  key: cloud-api-key
            - name: CLOUD_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: barca-secret
                  key: cloud-api-secret
            - name: CLIENT_URL
              value: 'https://barcaapp.info'
            - name: API_GATEWAY_URL
              value: 'http://barca-gateway.production.svc.cluster.local:4000'
            - name: ELASTIC_SEARCH_URL
              valueFrom:
                secretKeyRef:
                  name: barca-secret
                  key: barca-elasticsearch-url
            - name: ELASTIC_APM_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: barca-secret
                  key: barca-elastic-apm-server-url
            - name: ELASTIC_APM_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: barca-secret
                  key: barca-elastic-apm-secret-token
