apiVersion: apps/v1
kind: Deployment
metadata:
  name: barca-gateway
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: barca-gateway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: barca-gateway
    spec:
      containers:
        - name: barca-gateway
          image: joseph0926/barca-gateway:stable
          imagePullPolicy: Always
          resources:
            limits:
              cpu: '0.5'
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 150Mi
          ports:
            - name: gateway
              containerPort: 4000
          env:
            - name: ENABLE_APM
              value: '1'
            - name: NODE_ENV
              value: 'production'
            - name: SECRET_KEY_ONE
              valueFrom:
                secretKeyRef:
                  name: barca-secret
                  key: secret-key-one
            - name: SECRET_KEY_TWO
              valueFrom:
                secretKeyRef:
                  name: barca-secret
                  key: secret-key-two
            - name: GATEWAY_JWT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: barca-secret
                  key: gateway-jwt-token
            - name: JWT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: barca-secret
                  key: jwt-token
            - name: CLIENT_URL
              value: 'https://barcaapp.info'
            - name: AUTH_BASE_URL
              value: 'http://barca-auth.production.svc.cluster.local:4002'
            - name: USERS_BASE_URL
              value: 'http://barca-users.production.svc.cluster.local:4003'
            - name: GIG_BASE_URL
              value: 'http://barca-gig.production.svc.cluster.local:4004'
            - name: MESSAGE_BASE_URL
              value: 'http://barca-chat.production.svc.cluster.local:4005'
            - name: ORDER_BASE_URL
              value: 'http://barca-order.production.svc.cluster.local:4006'
            - name: REVIEW_BASE_URL
              value: 'http://barca-review.production.svc.cluster.local:4007'
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: barca-secret
                  key: barca-redis-host
            - name: ELASTIC_SEARCH_URL
              valueFrom:
                secretKeyRef:
                  name: barca-secret
                  key: barca-elasticsearch-url
            - name: ELASTIC_APM_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: barca-secret
                  key: barca-elastic-apm-server-url
            - name: ELASTIC_APM_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: barca-secret
                  key: barca-elastic-apm-secret-token
