apiVersion: apps/v1
kind: Deployment
metadata:
  name: barca-psql
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: barca-psql
  template:
    metadata:
      labels:
        app: barca-psql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: barca-psql
          image: postgres
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: barca-secret
                  key: barca-psql-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: barca-secret
                  key: barca-psql-password
            - name: POSTGRES_DB
              value: barca-review
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          resources:
            limits:
              memory: '1Gi'
              cpu: '0.5'
            requests:
              cpu: 100m
              memory: 150Mi
          ports:
            - name: barca-psql
              containerPort: 5432
          volumeMounts:
            - name: psql-local-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          readinessProbe:
            exec:
              command:
                [
                  'psql',
                  '-w',
                  '-U',
                  'barca',
                  '-d',
                  'barca_review',
                  '-c',
                  'SELECT 1',
                ]
            initialDelaySeconds: 120
            periodSeconds: 300
            timeoutSeconds: 60
          livenessProbe:
            exec:
              command:
                [
                  'psql',
                  '-w',
                  '-U',
                  'barca',
                  '-d',
                  'barca_review',
                  '-c',
                  'SELECT 1',
                ]
            initialDelaySeconds: 120
            periodSeconds: 300
            timeoutSeconds: 60
      volumes:
        - name: psql-local-storage
          persistentVolumeClaim:
            claimName: psql-pvc
