apiVersion: apps/v1
kind: Deployment
metadata:
  name: barca-mysql
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: barca-mysql
  template:
    metadata:
      labels:
        app: barca-mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: barca-mysql
          image: mysql:8.0.35
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: barca-secret
                  key: barca-mysql-password
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: barca-secret
                  key: barca-mysql-password
            - name: MYSQL_DATABASE
              value: jobber_auth
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: barca-secret
                  key: barca-mysql-user
          resources:
            limits:
              memory: '1Gi'
              cpu: '0.5'
            requests:
              cpu: 100m
              memory: 150Mi
          ports:
            - name: barca-mysql
              containerPort: 3306
          volumeMounts:
            - name: mysql-local-storage
              mountPath: /var/lib/mysql
              subPath: mysql
          readinessProbe:
            exec:
              command:
                - bash
                - '-c'
                - |
                  mysql -h127.0.0.1 -u$MYSQL_USER -p$MYSQL_PASSWORD -e'SELECT 1'
            initialDelaySeconds: 120
            periodSeconds: 300
            timeoutSeconds: 60
          livenessProbe:
            exec:
              command:
                - bash
                - '-c'
                - |
                  mysqladmin -u$MYSQL_USER -p$MYSQL_PASSWORD ping
            initialDelaySeconds: 120
            periodSeconds: 300
            timeoutSeconds: 60
      volumes:
        - name: mysql-local-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
