apiVersion: apps/v1
kind: Deployment
metadata:
  name: barca-review
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: barca-review
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: barca-review
    spec:
      containers:
        - name: barca-review
          image: joseph0926/barca-review:stable
          imagePullPolicy: Always
          resources:
            limits:
              memory: '1Gi'
              cpu: '0.5'
            requests:
              cpu: 100m
              memory: 150Mi
          ports:
            - name: review
              containerPort: 4007
          env:
            - name: ENABLE_APM
              value: '1'
            - name: NODE_ENV
              value: 'production'
            - name: CLUSTER_TYPE
              value: 'minikube'
            - name: GATEWAY_JWT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: barca-secret
                  key: gateway-jwt-token
            - name: JWT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: barca-secret
                  key: jwt-token
            - name: RABBITMQ_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: barca-secret
                  key: barca-rabbitmq-endpoint
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: barca-secret
                  key: barca-psql-host
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: barca-secret
                  key: barca-psql-user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: barca-secret
                  key: barca-psql-password
            - name: DATABASE_NAME
              value: 'barca_review'
            - name: CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: barca-secret
                  key: cloud-name
            - name: CLOUD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: barca-secret
                  key: cloud-api-key
            - name: CLOUD_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: barca-secret
                  key: cloud-api-secret
            - name: API_GATEWAY_URL
              value: 'http://barca-gateway.production.svc.cluster.local:4000'
            - name: ELASTIC_SEARCH_URL
              valueFrom:
                secretKeyRef:
                  name: barca-secret
                  key: barca-elasticsearch-url
            - name: ELASTIC_APM_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: barca-secret
                  key: barca-elastic-apm-server-url
            - name: ELASTIC_APM_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: barca-secret
                  key: barca-elastic-apm-secret-token
