apiVersion: v1
kind: Service
metadata:
  name: barca-review
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: barca-review
  ports:
    - name: review
      port: 4007
      targetPort: 4007
      protocol: TCP
